const PracticeLanguage = {
  vi: {
    id: 'Mã bài',
    name: 'Tên bài',
    solved: 'Số người giải',
    public: 'Công khai',
    hidden: 'ẩn bài',
    edit: 'Cập nhật',
    noProblem: 'Không có bài tập',
    statement: 'Đề bài',
    testCases: 'Test bài',
    tutorial: 'Hướng dẫn giải',
    share: 'Chia sẻ',
    upload: 'Lưu',
    publish: 'Đăng bài',
    remove: 'Xóa bài',
    allSubmissions: 'Tất cả bài nộp',
    mySubmissions: 'Bài nộp của tôi',
    editUppercase: 'CẬP NHẬT',
    inputStatement: 'Input',
    outputStatement: 'Output',
    inputTest: 'input',
    outputTest: 'output',
    notSupportVietnamese: 'Bài tập này chưa có phiên bản tiếng Việt hoặc đang được cập nhật!',
    notSupportEnglish: 'Bài tập này chưa có phiên bản tiếng Anh hoặc đang được cập nhật!',
    editorialUpdate: 'Hướng dẫn giải chưa được cập nhật!',
    idSubmission: 'Mã nộp bài',
    programmingLanguage: 'Ngôn ngữ',
    result: 'Kết quả',
    noSubmission: 'Không có bài nộp',
    notSupportVietnamesePlaceHolder: 'Chưa hỗ trợ Tiếng Việt',
    notSupportEnglishPlaceHolder: 'Chưa hỗ trợ Tiếng Anh',
    changeLanguage: 'Đổi ngôn ngữ',
    testcaseExplanation: 'Giải thích',
    submissionUser: 'Người nộp',
    uploader: 'Người đăng',
    cannotSubmit: 'Hết thời gian làm bài. Bạn không thể tiếp tục nộp bài!',
    timeout: 'Hết giờ',
    sourceCode: 'Mã nguồn tham khảo',
    time: 'Thời gian',
    memory: 'Bộ nhớ',
    problemCode: 'Mã bài',
    timeLimit: 'Giới hạn thời gian',
    memoryLimit: 'Giới hạn bộ nhớ',
    resource: 'Nguồn bài',
    type: 'Loại bài',
    difficulty: 'Độ khó',
    information: 'Thông tin',
    explanation: 'Giải thích ví dụ',
    'Very Easy': 'Rất dễ',
    Easy: 'Dễ',
    Medium: 'Trung bình',
    Hard: 'Khó',
    'Very Hard': 'Rất khó',
    Secret: 'Bí mật',
    status: 'Đã giải',
    newProblem: 'Các bài tập mới',
    update: 'Cập nhật',
    noTag: 'Không có tag',
    submitTime: 'Thời gian nộp',
    score: 'Điểm',
    example: 'Ví dụ',
    noNewProblem: 'Không có bài tập nào mới',
    discussion: 'Thảo luận',
  },
};

export default PracticeLanguage;
