const SidePanelLanguage = {
  en: {
    problemInformationTitle: 'Problem Information',
    timeLimit: 'Time limit',
    memoryLimit: 'Memory limit',
    source: 'Resource',
    searchProblemTitle: 'SEARCH',
    problem: 'Problem',
    searchProblemBar: 'problem name or ID',
    tags: 'Tags',
    searchProblemButton: 'Search',
    clearProblemButton: 'Clear',
    notAvailable: 'Not available',
    leaderboardTitle: 'LEADERBOARD',
    upcomingContestsTitle: 'UPCOMING CONTESTS',
    hotTopicsTitle: 'HOT TOPICS',
    difficulty: 'Difficulty',
    dataset: 'Dataset',
    nameContestLabel: 'Name',
    beforeContestLabel: 'Time before contest',
    daysLabel: 'days',
    hoursLabel: 'hours',
    minutesLabel: 'minutes',
    secondsLabel: 'seconds',
    filter: 'filter',
    user: 'User',
    seeAll: 'See All',
    noUpComingContest: 'No upcoming contests',
  },
  vi: {
    problemInformationTitle: 'Thông tin đề bài',
    timeLimit: 'Giới hạn thời gian',
    memoryLimit: 'Giới hạn bộ nhớ',
    source: 'Nguồn bài',
    searchProblemTitle: 'TÌM KIẾM BÀI TẬP',
    problem: 'Bài tập',
    searchProblemBar: 'Tên bài tập hoặc Mã bài',
    tags: 'Thẻ',
    searchProblemButton: 'Tìm kiếm',
    clearProblemButton: 'Xóa',
    notAvailable: 'Không khả dụng',
    leaderboardTitle: 'BẢNG XẾP HẠNG',
    upcomingContestsTitle: 'KỲ THI SẮP TỚI',
    hotTopicsTitle: 'BÀI VIẾT NỔI BẬT',
    difficulty: 'Độ khó',
    dataset: 'Bộ test',
    nameContestLabel: 'Tên kỳ thi',
    beforeContestLabel: 'Thời gian đến kỳ thi',
    daysLabel: 'ngày',
    hoursLabel: 'giờ',
    minutesLabel: 'phút',
    secondsLabel: 'giây',
    filter: 'lọc',
    user: 'Học viên',
    seeAll: 'Xem BXH đầy đủ',
    noUpComingContest: 'Không có kỳ thi nào sắp tới',
  },
};

export default SidePanelLanguage;
